title = "Repo-Compliance gitleaks config"

[allowlist]
description = "Ignora secretos sint√©ticos usados en pruebas"

paths = [
    '''tests/test_rule_secrets_none\.py''',
    '''tests/test_secrest_multifile\.py'''
]

regexes = [
    '''REDACTED'''
]
